### ISSUE TITLE
User acceptance issues

### ISSUE THREAD

**Issue by jpowell** [watermarkchurch/theporch-apollos#155]
- [x] hide share for announcements like we did for events - it doesn't work
- [x] allow pinch zoom on location maps to stay when zoomed in (like CLC)

There are also a few bugsnags that are recurring

![image](https://user-images.githubusercontent.com/35932/131185572-b37062e0-31d6-4187-b4dd-57a9c7c1c366.png)

**Comment by conrad-vanl** [comment]
Fixed the acceptance issues, just pushed up. will be in next build. I'll promote to production as soon as I can but because of my schedule (Covid, kids home, etc) you are welcome to push the buttons if you see it come through sooner then I do. We can promote to production as soon as TestFlight build becomes available.

For the bugsnag issues - those look like issues that should be fixed in a new version of Apollos, that are related to issues with queries firing during loading states. Shouldn't cause any frontend issues, just will muck up bugsnag history.
